app_name: 'artist2artist-gravity'

dataset:
  path: "../Datasets"
  name: "cora"

model:
  name: "VAE"
  subgraph:
    rate: .10
    method: "degree"
    alpha: 2.
    replace: False
  layer:
    hidden_dim_1: 64
    hidden_dim_2: 33
    dropout_rate: 0.
  early_stop: 
    start: 10 
    patience: 10
    delta: 0
  validation:
    rate: 10.
    step: 100
  test:
    rate: 10.
    split: 100
  pop_bias: 10.
  normalize: True
  epoch: 10
  lr: 0.01
  test_rate: 10.

inference:
  path:
    artifact: "artifact"
    embedding: "emb.npy"
    index2node: "index2node.json"
    similar_artists: "similar_artists.csv"
  emb_split_size: 100
